services:
  mysql:
    image: mysql:latest
    container_name: tcl_db
    environment:
      MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - ".env.development.local"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d