services:
  mysql:
    image: mysql:latest
    container_name: tcl_db
    env_file:
      - .env.development.local
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./backup:/docker-entrypoint-initdb.d